### ISSUE TITLE
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Comeet' does not have a method 'filter_url' in class-wp-hook.php on line 286

### ISSUE THREAD

**Issue by joelandrewbrown** [YonatanRan/comeet-wp-plugin#1]
I am getting this warning: Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Comeet' does not have a method 'filter_url' in class-wp-hook.php on line 286.

I'm using Wordpress 4.9.6. I'm using the a Divi child theme I've created. I've verified that even when I switch themes to a default WP theme such as TwentySeventeen the warning persists.

I've simply dropped [comeet_data] into the default WP editor. Attached are a couple screenshots.

Any ideas? Thanks!

![screen shot 2018-06-25 at 11 08 19 am](https://user-images.githubusercontent.com/1489911/41861926-24cc1a48-7868-11e8-8307-f5eea0f7ff5a.png)
![screen shot 2018-06-25 at 11 08 04 am](https://user-images.githubusercontent.com/1489911/41861927-24dc1d9e-7868-11e8-9469-a1786447eeee.png)
![screen shot 2018-06-25 at 11 07 43 am](https://user-images.githubusercontent.com/1489911/41861928-24eae522-7868-11e8-95b0-649d613f757d.png)

**Comment by YonatanRan** [comment]
Hi @joelandrewbrown, Thanks for letting me know about this. I'll check/fix this and update everything. 
This shouldn't take to long, so I'll let you know when it's updated.

Again, thanks!

**Comment by joelandrewbrown** [comment]
@YonatanRan - thanks so much. I just moved all my staging stuff locally, so I can customize some things, and ran into a few Deprecated functions as well. Think that's an easy fix also? please see screenshot - "Deprecated: Non-static method Comeet::plugin_debug() should not be called statically in /Users/joelbrown/sites/yaro-landing/wp-content/plugins/comeet-wp-plugin-master/includes/lib/comeet-data.php on line 158"

![screen shot 2018-06-25 at 11 43 00 am](https://user-images.githubusercontent.com/1489911/41863681-29562130-786d-11e8-8377-4e39ebc36554.png)

**Comment by YonatanRan** [comment]
Hi @joelandrewbrown.

I went ahead and fixed all the issues you encountered. So yo can now update to the latest version (2.0.1.0) and stuff should work as expected, with no warnings or notifications.

Thanks!

**Comment by joelandrewbrown** [comment]
@YonatanRan thank you so much! Worked like a charm.

**Comment by joelandrewbrown** [comment]
@YonatanRan - One more thing, it is not crippling me, but I always dislike when the console is throwing me errors. Please see screenshot of my console and let me know what you think!
![screen shot 2018-06-25 at 3 02 02 pm](https://user-images.githubusercontent.com/1489911/41872877-e10331d6-7888-11e8-8192-89f17bd6acc4.png)

**Comment by YonatanRan** [comment]
@joelandrewbrown  That always happens when working on a local env, but doesn't once the system is on a production server.

Once you deploy, if this still happens, let me know and I will check what the deal is...

**Comment by joelandrewbrown** [comment]
@YonatanRan - Thanks so much for your responsiveness. We're officially all live and secure.

Our jobs are posting here just fine: https://goyaro.com/careers/

When you click on the only job posted so far it takes you here: https://goyaro.com/careers/co/engineering/01.906/senior-software-engineer/all/

See the screenshot attached, I'm still seeing the error in the console. When I click the buttons at the bottom of the post the console throws more errors too.

Again, everything seems to be working fine, I just never like it when there are console errors if I can help it!

![screen shot 2018-06-27 at 2 14 04 pm](https://user-images.githubusercontent.com/1489911/41994582-85376b0a-7a14-11e8-872d-c9cb4c569c99.png)

![job opportunity senior software engineer 2018-06-27 14-15-58](https://user-images.githubusercontent.com/1489911/41994674-d3f786da-7a14-11e8-92bd-2a65d6047e85.png)

**Comment by joelandrewbrown** [comment]
Sounds good, thanks so much!

Joel Brown
jabcreative.co
joel@joelandrewbrown.com
(312) 319-4449
